pipeline {
    agent any
    environment {
        dockerHome = tool "myDocker"
        mavenHome = tool "myMaven"
        PATH ="$dockerHome/bin:$mavenHome/bin:$PATH"
    }
    stages{
        stage('Checkout'){
            steps {
                sh "mvn --version"
                sh "docker version"
                echo "BUILD"
                echo "PATH = $PATH"
                echo "BUILD_NUMBER = $env.BUILD_NUMBER"
                echo "BUILD_ID = $env.BUILD_ID"
                echo "JOB_NAME =$env.JOB_NAME"
                echo "BUILD_TAG =$env.BUILD_TAG"
                echo "BUILD_URL = $env.BUILD_URL"
            }
        }
        stage('Compile'){
            steps{
                sh """cd currency-exchange-microservice
                    mvn clean compile"""
            }
        }
        stage('Test'){
            steps{
                sh """cd currency-exchange-microservice
                mvn test"""
            }
        }
        stage('Integration Test'){
            steps{
                sh """cd currency-exchange-microservice
                mvn failsafe:integration-test failsafe:verify"""
            }
        }
    }
}    