pipeline {
    agent any
    environment {
        dockerHome = tool "myDocker"
        mavenHome = tool "myMaven"
        PATH ="$dockerHome/bin:$mavenHome/bin:$PATH"
    }
    stages{
        stage('Build'){
            steps {
                sh "mvn --version"
                sh "docker --version"
            }
        }
        stage('Test'){
            steps {
                echo "Test"
            }
        }
        stage('Integration Test'){
            steps{
                echo "Integration Test"
            }
        }
    } 
    
    post {
        always {
            echo "I am awsome. I run always"
        }
        success {
            echo " I run when you are successful"
        }
        failure {
            echo " I run when you fail"
        }
    }
}
