pipeline {
    agent any
    stages{
        stage('Build'){
            steps {
                echo "Build"
                echo "PATH=$PATH"
                echo "BUILD_NUMBER=$env.BUILD_NUMBER"
                echo "JOB_NAME =$env.JOB_NAME"
                echo "BUILD_TAG =$env.BUILD_TAG"
            }
        }
        stage('Test'){
            steps {
                echo "Test"
            }
        }
        stage('Integration Test'){
            steps{
                echo "Integration Test"
            }
        }
    } 
    
    post {
        always {
            echo "I am awsome. I run always"
        }
        success {
            echo " I run when you are successful"
        }
        failure {
            echo " I run when you fail"
        }
    }
}
